# Generated by Django 4.2.13 on 2024-06-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_lessons_ulesson_unit_uunit_delete_signals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ulesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
