# Generated by Django 4.2.13 on 2024-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alter_ulesson_image_alter_ulesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
