# Generated by Django 4.2.13 on 2024-06-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_userresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['level'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
