# Generated by Django 4.2.13 on 2024-07-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_alter_unit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='ico',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ulesson',
            name='ico',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
