# Generated by Django 4.2.13 on 2024-07-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_unit_diagnostic_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='diagnostic_completed',
        ),
    ]
