# Generated by Django 4.2.13 on 2024-06-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoundHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'RoundHistory',
                'verbose_name_plural': 'RoundHistorys',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Socre',
                'verbose_name_plural': 'Socres',
            },
        ),
    ]
