# Generated by Django 4.2.13 on 2024-06-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_roundhistory_user_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roundhistory',
            name='game',
            field=models.SmallIntegerField(choices=[(1, 'Box'), (2, 'Memory'), (3, 'Option 3')], default=1),
        ),
    ]
