# Generated by Django 4.2.13 on 2024-06-30 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_roundhistory_created_at_roundhistory_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundhistory',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
