# Generated by Django 4.2.13 on 2024-06-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.IntegerField(default=0)),
                ('response', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ItemTest',
                'verbose_name_plural': 'ItemTests',
            },
        ),
    ]
