# Generated by Django 4.2.13 on 2024-07-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_diagnostic_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='profesor', max_length=20),
        ),
    ]
